version: '3.9'
services :
  app:
    container_name: spring-app
    build:
      dockerfile: Dockerfile
    image: spring-app:latest
    ports:
      - "8082:8082"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge      